<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
  <!ELEMENT students (student+)>
  <!ELEMENT student (name, email, address)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT address (street, city, state, zip)>
  <!ELEMENT street (#PCDATA)>
  <!ELEMENT city (#PCDATA)>
  <!ELEMENT state (#PCDATA)>
  <!ELEMENT zip (#PCDATA)>
]>
<students>
  <student>
    <name>Jisoo Kim</name>
    <email>jisoo.kim@gmail.com</email>
    <address>
      <street>123 Main St</street>
      <city>Seoul</city>
      <state>Korea</state>
      <zip>10001</zip>
    </address>
  </student>
  <student>
    <name>Rose Park</name>
    <email>park.rose@gmail.com</email>
    <address>
      <street>456 Elm St</street>
      <city>Itaewon</city>
      <state>Melbourne</state>
      <zip>90001</zip>
    </address>
  </student>
</students>
